language: node_js
node_js:
  - "0.10"

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    # travis-encrypt -r martinmicunda/employee-scheduling-ui GH_TOKEN=<https://help.github.com/articles/creating-an-access-token-for-command-line-use> --add env.global
    - secure: cQyV8hRn1z3yHxuj2ZIGdvS1lRJJEDpNs/cS/4In/QFuq6JR1m/QxZGlJghLqMa/xfdNi0C2u0lpY7AYTPiTByotR8mGfbJHM9wpcFBQuMILclKkta0i9tZDfbog9UQG/ZAGhe+9IR0VsYLTvZTu/8qwH3wywls9sWTn7TDoBl0=
    # COVERALLS_REPO_TOKEN
#    - secure: YDGbgsTSvN9evJIRhX22Y+P56VYK50bT1tnQrkMxLRANyyQc6UF/e5iKWm+Yy4/0OWq12o+2tTvBc/MgdwSE+t28E+VmdF/JcQDY2pHb8szQ6PjS1PCkeq3IbYvdsYTSAWOBa9coqXECwkwEdtI6tuGQpXL/MOnq7ZncOetdpF4=

# starts xvfb on display port :99.0 (virtual display for Firefox)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - bash -ex ./bin/ci_build.sh

