language: node_js
node_js:
  - "0.10"

notifications:
  email:
    on_success: never
    on_failure: always

# starts xvfb on display port :99.0 (virtual display for Firefox)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g jspm"

# install dependencies necessary to run this build
install:
  - npm install --quiet

script:
  - bash -ex ./ci_build.sh

